from __future__ import annotations

import json
from typing import Any

LABELS = {
    "RUN_CREATED": "RUN", "RUN_STARTED": "RUN", "RUN_COMPLETED": "DONE",
    "RUN_FAILED": "FAILED", "RUN_STOPPED": "STOPPED", "STATISTICAL_STATE_CREATED": "STATE",
    "JEV_WIDE_STATE_EVALUATED": "JEV WIDE", "CANDIDATE_PROMOTED": "CANDIDATE",
    "EVIDENCE_STATE_CREATED": "EVIDENCE", "JEV_DEEP_COMPLETED": "JEV DEEP",
    "HYPOTHESES_GENERATED": "HYPOTHESES", "FOLLOWUP_COMPLETED": "FOLLOWUP",
    "DOSSIER_CREATED": "DOSSIER",
    "GDC_REQUEST_STARTED": "GDC", "GDC_REQUEST_COMPLETED": "GDC", "GDC_REQUEST_FAILED": "GDC FAILED",
    "GDC_CACHE_HIT": "GDC CACHE", "GDC_RESPONSE_LIMIT_EXCEEDED": "GDC LIMIT",
    "GDC_REQUEST_BUDGET_EXHAUSTED": "GDC BUDGET", "GDC_RUN_BYTE_BUDGET_EXHAUSTED": "GDC BUDGET",
    "INVENTORY_STARTED": "INVENTORY", "INVENTORY_COMPLETED": "INVENTORY",
    "PROJECT_SCOPE_SELECTED": "SCOPE", "WIDE_SCAN_STARTED": "WIDE", "WIDE_SCAN_COMPLETED": "WIDE",
    "JEV_PROJECTION_CREATED": "PROJECTION", "JEV_WIDE_STARTED": "JEV WIDE",
    "JEV_WIDE_COMPLETED": "JEV WIDE", "JEV_EVALUATION_FAILED": "JEV FAILED",
    "WIDE_RANKING_COMPLETED": "RANKING",
}


def render_event(event: dict[str, Any]) -> None:
    label = LABELS.get(event["type"], event.get("stage") or "EVENT")
    print(f"[{label}] #{event['sequence']} {event['message']}", flush=True)


def render_json_event(event: dict[str, Any]) -> None:
    print(json.dumps(event, indent=2, sort_keys=True), flush=True)

