from enum import StrEnum


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"


class CandidateStatus(StrEnum):
    NEW = "NEW"
    WIDE_EVALUATED = "WIDE_EVALUATED"
    DEEP_ANALYZED = "DEEP_ANALYZED"
    HYPOTHESIZED = "HYPOTHESIZED"
    FOLLOWUP = "FOLLOWUP"
    DOSSIER_READY = "DOSSIER_READY"
    TERMINATED = "TERMINATED"
    DEFERRED = "DEFERRED"
    FAILED = "FAILED"


STAGES = (
    "INVENTORY", "GDC_FAST_SEARCH", "STATE_GENERATION", "JEV_WIDE",
    "DEEP_ANALYSIS", "EVIDENCE_BUILD", "JEV_DEEP", "HYPOTHESIS_GENERATION",
    "HYPOTHESIS_VERIFICATION", "FOLLOWUP", "DOSSIER",
)

